<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class UserSeeder extends Seeder
{
    public function run()
    {
        $users = [
            [
                'name' => 'M.Ilham Firdaus',
                'email' => 'ilhamfirdaus@gmail.com',
                'password' => Hash::make('ilhamfirdaus'),
                'email_verified_at' => Carbon::parse('2024-04-25 19:13:35'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RENI ERAWATI',
                'email' => 'erawatireni89@gmail.com',
                'password' => Hash::make('erawatireni89'),
                'email_verified_at' => Carbon::parse('2024-04-25 19:13:35'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'YAYAH JUHAERIYAH',
                'email' => 'yayah531973@gmail.com',
                'password' => Hash::make('yayah531973'),
                'email_verified_at' => Carbon::parse('2025-06-20 12:47:41'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'YENIMAISARI',
                'email' => 'yenimaisari66@gmail.com',
                'password' => Hash::make('yenimaisari66'),
                'email_verified_at' => Carbon::parse('2025-01-18 08:03:07'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'INAYAH',
                'email' => 'inayah01999@gmail.com',
                'password' => Hash::make('inayah01999'),
                'email_verified_at' => Carbon::parse('2025-06-01 09:14:15'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HAERIAH',
                'email' => 'haeriah0502@gmail.com',
                'password' => Hash::make('haeriah0502'),
                'email_verified_at' => Carbon::parse('2024-12-24 16:08:02'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'YAYAH SUHAYAH',
                'email' => 'yayahsuhayah311@gmail.com',
                'password' => Hash::make('yayahsuhayah311'),
                'email_verified_at' => Carbon::parse('2024-08-01 06:38:11'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NURHASANAH',
                'email' => 'syahaelabae@gmail.com',
                'password' => Hash::make('syahaelabae'),
                'email_verified_at' => Carbon::parse('2024-07-19 07:29:17'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HELVI HERLINA',
                'email' => 'helviherliana33@gmail.com',
                'password' => Hash::make('helviherliana33'),
                'email_verified_at' => Carbon::parse('2024-08-11 03:10:27'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RODIAH',
                'email' => 'rodiah811982@gmail.com',
                'password' => Hash::make('rodiah811982'),
                'email_verified_at' => Carbon::parse('2024-06-25 15:00:03'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NINGMAS',
                'email' => 'ningmas411@gmail.com',
                'password' => Hash::make('ningmas411'),
                'email_verified_at' => Carbon::parse('2024-02-18 20:43:55'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TIA YULIANAWATI',
                'email' => 'tyayulianawati3@gmail.com',
                'password' => Hash::make('tyayulianawati3'),
                'email_verified_at' => Carbon::parse('2024-10-25 12:29:34'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SITI NURJANAH',
                'email' => 'sitinurjanah21021997@gmail.com',
                'password' => Hash::make('sitinurjanah21021997'),
                'email_verified_at' => Carbon::parse('2024-07-08 13:32:38'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MUNAWAROH',
                'email' => 'munawaroh07081968@gmail.com',
                'password' => Hash::make('munawaroh07081968'),
                'email_verified_at' => Carbon::parse('2024-08-04 04:55:32'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'IMMAS MASYRIFAH',
                'email' => 'nimasrifah2@gmail.com',
                'password' => Hash::make('nimasrifah2'),
                'email_verified_at' => Carbon::parse('2024-08-04 05:03:10'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NURNANINGSIH',
                'email' => 'nurnaningsih12091972@gmail.com',
                'password' => Hash::make('nurnaningsih12091972'),
                'email_verified_at' => Carbon::parse('2024-07-25 06:36:20'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NUR HIKMAWATI',
                'email' => 'nurhikmawati441@gmail.com',
                'password' => Hash::make('nurhikmawati441'),
                'email_verified_at' => Carbon::parse('2025-02-06 20:41:55'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MUTMAINAH',
                'email' => 'mutmainah4415@gmail.com',
                'password' => Hash::make('mutmainah4415'),
                'email_verified_at' => Carbon::parse('2024-07-23 10:28:45'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AYU WULANDARI',
                'email' => 'rey458048@gmail.com',
                'password' => Hash::make('rey458048'),
                'email_verified_at' => Carbon::parse('2024-09-29 19:01:49'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SUHARTI',
                'email' => 'suharti09011977@gmail.com',
                'password' => Hash::make('suharti09011977'),
                'email_verified_at' => Carbon::parse('2025-07-24 18:14:24'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ELINDA RAHMAWATI',
                'email' => 'elinda.26.er@gmail.com',
                'password' => Hash::make('elinda.26.er'),
                'email_verified_at' => Carbon::parse('2024-04-16 04:05:15'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PEGGY SULASTRIANI',
                'email' => 'peggysulastriani@gmail.com',
                'password' => Hash::make('peggysulastriani'),
                'email_verified_at' => Carbon::parse('2024-02-23 20:36:19'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SITI ENDARTI',
                'email' => 'sitiendarti140373@gmail.com',
                'password' => Hash::make('sitiendarti140373'),
                'email_verified_at' => Carbon::parse('2024-11-17 19:45:24'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NOPI INDRIANI',
                'email' => 'indrianinopi18@gmail.com',
                'password' => Hash::make('indrianinopi18'),
                'email_verified_at' => Carbon::parse('2024-02-21 13:20:29'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'IWA KOMALASARI',
                'email' => 'iwaprakerja@gmail.com',
                'password' => Hash::make('iwaprakerja'),
                'email_verified_at' => Carbon::parse('2024-12-17 17:58:55'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'IDAH ROLIDAH',
                'email' => 'srinita2345@gmail.com',
                'password' => Hash::make('srinita2345'),
                'email_verified_at' => Carbon::parse('2024-10-14 14:39:10'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JUHA IRAWATI',
                'email' => 'juhairawati3@gmail.com',
                'password' => Hash::make('juhairawati3'),
                'email_verified_at' => Carbon::parse('2024-10-04 08:31:33'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MAEMUNAH',
                'email' => 'maemunah1469@gmail.com',
                'password' => Hash::make('maemunah1469'),
                'email_verified_at' => Carbon::parse('2025-07-22 09:49:32'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GINA ROSLIANA',
                'email' => 'ginarosliana04@gmail.com',
                'password' => Hash::make('ginarosliana04'),
                'email_verified_at' => Carbon::parse('2024-05-01 00:58:59'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NURHASAN',
                'email' => 'nurhasan29011998@gmail.com',
                'password' => Hash::make('nurhasan29011998'),
                'email_verified_at' => Carbon::parse('2025-06-06 07:55:55'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SITI ROBIATUL ADAWIYAH',
                'email' => 'ndaloveaby01@gmail.com',
                'password' => Hash::make('ndaloveaby01'),
                'email_verified_at' => Carbon::parse('2025-07-15 07:22:38'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'UMIDATUL KHUMAIROH',
                'email' => 'umidatulkhumairoh1@gmail.com',
                'password' => Hash::make('umidatulkhumairoh1'),
                'email_verified_at' => Carbon::parse('2024-10-27 22:19:11'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'KASTI',
                'email' => 'adeadiriyana123@gmail.com',
                'password' => Hash::make('adeadiriyana123'),
                'email_verified_at' => Carbon::parse('2024-07-20 01:31:30'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SRINITA',
                'email' => 'srinitanita977@gmail.com',
                'password' => Hash::make('srinitanita977'),
                'email_verified_at' => Carbon::parse('2024-09-12 22:59:17'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SITI AMINAH',
                'email' => 'asiti02041979@gmail.com',
                'password' => Hash::make('asiti02041979'),
                'email_verified_at' => Carbon::parse('2025-04-16 23:35:14'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TOHARI',
                'email' => 'tohariecih@gmail.com',
                'password' => Hash::make('tohariecih'),
                'email_verified_at' => Carbon::parse('2025-01-29 12:45:30'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NURMAULANA FAJRI',
                'email' => 'fazri123aja@gmail.com',
                'password' => Hash::make('fazri123aja'),
                'email_verified_at' => Carbon::parse('2025-02-23 01:28:57'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GUNAWAN ALAMSYAH',
                'email' => 'gunawanalamsyah30@gmail.com',
                'password' => Hash::make('gunawanalamsyah30'),
                'email_verified_at' => Carbon::parse('2024-01-03 15:48:44'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'WIWIN DEWI NINGSIH',
                'email' => 'wiwindewiningsih912@gmail.com',
                'password' => Hash::make('wiwindewiningsih912'),
                'email_verified_at' => Carbon::parse('2025-01-20 09:42:39'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SITI AISAH',
                'email' => 'aisahsiti3541@gmail.com',
                'password' => Hash::make('aisahsiti3541'),
                'email_verified_at' => Carbon::parse('2024-06-09 17:23:46'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SUHEMI',
                'email' => 'suhemi14061979@gmail.com',
                'password' => Hash::make('suhemi14061979'),
                'email_verified_at' => Carbon::parse('2024-09-20 06:13:59'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'KURNIA SARI',
                'email' => 'kurniasarimaret19@gmail.com',
                'password' => Hash::make('kurniasarimaret19'),
                'email_verified_at' => Carbon::parse('2024-09-20 19:18:52'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HERAWATI',
                'email' => 'hherawatiy@gmail.com',
                'password' => Hash::make('hherawatiy'),
                'email_verified_at' => Carbon::parse('2024-02-26 17:33:37'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RUMINAH',
                'email' => 'ruminah11101963@gmail.com',
                'password' => Hash::make('ruminah11101963'),
                'email_verified_at' => Carbon::parse('2025-03-20 20:15:33'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'IKAH ATIKAH',
                'email' => 'ikahatikah968@gmail.com',
                'password' => Hash::make('ikahatikah968'),
                'email_verified_at' => Carbon::parse('2024-11-02 02:37:27'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ACIH',
                'email' => 'aciha1333@gmail.com',
                'password' => Hash::make('aciha1333'),
                'email_verified_at' => Carbon::parse('2024-05-17 06:40:06'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SUMIYATI',
                'email' => 'sumiyati87951@gmail.com',
                'password' => Hash::make('sumiyati87951'),
                'email_verified_at' => Carbon::parse('2024-05-28 07:32:44'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LISA SULISTIA',
                'email' => 'lisasulistia04@gmail.com',
                'password' => Hash::make('lisasulistia04'),
                'email_verified_at' => Carbon::parse('2025-08-05 04:22:24'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JOENATI',
                'email' => 'joenati753@gmail.com',
                'password' => Hash::make('joenati753'),
                'email_verified_at' => Carbon::parse('2024-05-01 21:31:54'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NIKE AYUNING TIAS',
                'email' => 'nikeayuningtias@gmail.com',
                'password' => Hash::make('nikeayuningtias'),
                'email_verified_at' => Carbon::parse('2024-06-11 14:02:11'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NURLELASARI',
                'email' => 'nurlaelasari928@gmail.com',
                'password' => Hash::make('nurlaelasari928'),
                'email_verified_at' => Carbon::parse('2025-01-25 01:35:42'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ADE SULASTRi',
                'email' => 'sulastrisulastri9092@gmail.com',
                'password' => Hash::make('sulastrisulastri9092'),
                'email_verified_at' => Carbon::parse('2024-07-25 08:21:24'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NUNUNG NURMASIAH',
                'email' => 'nunungnurmasiah@gmail.com',
                'password' => Hash::make('nunungnurmasiah'),
                'email_verified_at' => Carbon::parse('2024-05-19 07:09:17'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RAMA NUGRAHA',
                'email' => 'ramanugraha736@gmail.com',
                'password' => Hash::make('ramanugraha736'),
                'email_verified_at' => Carbon::parse('2025-05-24 15:21:22'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AYU UNANUNGSIH',
                'email' => 'ayuunaningsih@gmail.com',
                'password' => Hash::make('ayuunaningsih'),
                'email_verified_at' => Carbon::parse('2025-06-13 12:47:44'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ATI SUHARYATI',
                'email' => 'atisuharyati51@gmail.com',
                'password' => Hash::make('atisuharyati51'),
                'email_verified_at' => Carbon::parse('2025-06-07 16:45:58'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MU\'MINATUL JANNAH',
                'email' => 'jmuminatul@gmail.com',
                'password' => Hash::make('jmuminatul'),
                'email_verified_at' => Carbon::parse('2024-07-30 12:53:12'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'FIFIT ZUHERIYAH',
                'email' => 'abeliaputri1905@gmail.com',
                'password' => Hash::make('abeliaputri1905'),
                'email_verified_at' => Carbon::parse('2024-11-19 15:45:42'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SRI RAHAYU',
                'email' => 'srahayu30031983@gmail.com',
                'password' => Hash::make('srahayu30031983'),
                'email_verified_at' => Carbon::parse('2024-09-24 05:12:09'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TIA PUSPARANI',
                'email' => 'tiapusparani7@gmail.com',
                'password' => Hash::make('tiapusparani7'),
                'email_verified_at' => Carbon::parse('2024-07-14 07:35:25'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MUHAMMAD ALIMUDDIN',
                'email' => 'alimuddinarrojabi@gmail.com',
                'password' => Hash::make('alimuddinarrojabi'),
                'email_verified_at' => Carbon::parse('2024-03-03 12:27:27'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MARPUAH',
                'email' => 'marpuah9536@gmail.com',
                'password' => Hash::make('marpuah9536'),
                'email_verified_at' => Carbon::parse('2024-04-18 20:17:05'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ISAH',
                'email' => 'isahisah12101995@gmail.com',
                'password' => Hash::make('isahisah12101995'),
                'email_verified_at' => Carbon::parse('2025-07-14 08:14:11'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HAERUNNISA',
                'email' => 'haerunisa822@gmail.com',
                'password' => Hash::make('haerunisa822'),
                'email_verified_at' => Carbon::parse('2024-07-08 06:34:42'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'EYON YUGARIA',
                'email' => 'eyonyugaria@gmail.com',
                'password' => Hash::make('eyonyugaria'),
                'email_verified_at' => Carbon::parse('2025-03-11 04:27:55'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JAJAT SUDRAJAT',
                'email' => 'jajatsudrajat.paprjj@gmail.com',
                'password' => Hash::make('jajatsudrajat.paprjj'),
                'email_verified_at' => Carbon::parse('2024-03-26 07:27:09'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LUFI MAYSAROH',
                'email' => 'lufimaysaroh@gmail.com',
                'password' => Hash::make('lufimaysaroh'),
                'email_verified_at' => Carbon::parse('2024-06-30 10:20:40'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LILI ALIAH',
                'email' => 'lilialiah34@gmail.com',
                'password' => Hash::make('lilialiah34'),
                'email_verified_at' => Carbon::parse('2025-07-20 13:52:58'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GEVIRANA ZURAYA SHOFA',
                'email' => 'geviranazurayashofa15@gmail.com',
                'password' => Hash::make('geviranazurayashofa15'),
                'email_verified_at' => Carbon::parse('2024-11-24 01:15:29'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SODIKIN',
                'email' => 'sodikin07911010@gmail.com',
                'password' => Hash::make('sodikin07911010'),
                'email_verified_at' => Carbon::parse('2024-08-07 14:47:49'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NENI NURHAENI',
                'email' => 'mamahendin587@gmail.com',
                'password' => Hash::make('mamahendin587'),
                'email_verified_at' => Carbon::parse('2025-07-11 06:27:46'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RONIAH',
                'email' => 'roniah20051979@gmail.com',
                'password' => Hash::make('roniah20051979'),
                'email_verified_at' => Carbon::parse('2025-05-18 11:31:28'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MARI SAHUS',
                'email' => 'marisahus85@gmail.com',
                'password' => Hash::make('marisahus85'),
                'email_verified_at' => Carbon::parse('2025-03-25 08:53:08'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SALIMAH',
                'email' => 'salimah7251@gmail.com',
                'password' => Hash::make('salimah7251'),
                'email_verified_at' => Carbon::parse('2024-07-02 05:06:39'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CASINI',
                'email' => 'casini156@gmail.com',
                'password' => Hash::make('casini156'),
                'email_verified_at' => Carbon::parse('2025-07-23 05:28:58'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'IIN INDRAYANI',
                'email' => 'iinindrayanicrb234@gmail.com',
                'password' => Hash::make('iinindrayanicrb234'),
                'email_verified_at' => Carbon::parse('2025-03-16 10:55:43'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TIARA PUSPA RANI',
                'email' => 'tiarapuspa405@gmail.com',
                'password' => Hash::make('tiarapuspa405'),
                'email_verified_at' => Carbon::parse('2024-07-03 17:14:36'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RAMINAH',
                'email' => 'raminah240662@gmail.com',
                'password' => Hash::make('raminah240662'),
                'email_verified_at' => Carbon::parse('2024-04-04 14:49:19'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'YOYOH MAESAROH',
                'email' => 'tp3332032@gmail.com',
                'password' => Hash::make('tp3332032'),
                'email_verified_at' => Carbon::parse('2025-02-17 23:55:46'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'EMIN CARMINAH',
                'email' => 'emincarminah421@gmail.com',
                'password' => Hash::make('emincarminah421'),
                'email_verified_at' => Carbon::parse('2025-04-26 23:49:30'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DINDA AULIYA SYAPIRA',
                'email' => 'auliyadindasyapira466@gmail.com',
                'password' => Hash::make('auliyadindasyapira466'),
                'email_verified_at' => Carbon::parse('2024-03-26 07:22:52'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NURHAYATI',
                'email' => 'noerhayatinoer66@gmail.com',
                'password' => Hash::make('noerhayatinoer66'),
                'email_verified_at' => Carbon::parse('2025-01-01 00:00:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RAMOT DARYANTY',
                'email' => 'daryantyr@gmail.com',
                'password' => Hash::make('daryantyr'),
                'email_verified_at' => Carbon::parse('2025-01-11 16:56:28'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TEGUH BANGKIT',
                'email' => 'teguhbangkit23@gmail.com',
                'password' => Hash::make('teguhbangkit23'),
                'email_verified_at' => Carbon::parse('2025-01-22 09:52:56'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'THEOFILUS HATORANGAN NAPITUPULU',
                'email' => 'napitupulutheo4@gmail.com',
                'password' => Hash::make('napitupulutheo4'),
                'email_verified_at' => Carbon::parse('2025-02-02 02:49:24'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'FAJAR MALLO NAPITUPULU',
                'email' => 'fajarmallon@gmail.com',
                'password' => Hash::make('fajarmallon'),
                'email_verified_at' => Carbon::parse('2025-02-12 19:45:52'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'IIS SASTIAWATi',
                'email' => 'iissastiawati3@gmail.com',
                'password' => Hash::make('iissastiawati3'),
                'email_verified_at' => Carbon::parse('2025-02-23 12:42:21'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TRIAS PURNOMO',
                'email' => 'triaspurnomo95@gmail.com',
                'password' => Hash::make('triaspurnomo95'),
                'email_verified_at' => Carbon::parse('2025-03-06 05:38:49'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SANTI',
                'email' => 'santisanti22021987@gmail.com',
                'password' => Hash::make('santisanti22021987'),
                'email_verified_at' => Carbon::parse('2025-03-16 22:35:17'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DEDE YUSUF',
                'email' => 'yusufdede5991@gmail.com',
                'password' => Hash::make('yusufdede5991'),
                'email_verified_at' => Carbon::parse('2025-03-27 15:31:45'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MUHAMMAD SYAHRIL COTO',
                'email' => 'muhammadsyahril090504@gmail.com',
                'password' => Hash::make('muhammadsyahril090504'),
                'email_verified_at' => Carbon::parse('2025-04-07 08:28:14'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'VENNY IRAWATY',
                'email' => 'vennyirawaty24@gmail.com',
                'password' => Hash::make('vennyirawaty24'),
                'email_verified_at' => Carbon::parse('2025-04-18 01:24:42'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MUHAMMAD RAFLI',
                'email' => 'muhammadrafli042000@gmail.com',
                'password' => Hash::make('muhammadrafli042000'),
                'email_verified_at' => Carbon::parse('2025-04-28 18:21:10'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'FAJRI WICAKSANA',
                'email' => 'fajri.wicaksana@gmail.com',
                'password' => Hash::make('fajri.wicaksana'),
                'email_verified_at' => Carbon::parse('2025-05-09 11:17:38'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RIZKI AULIA',
                'email' => 'auliarizki6991@gmail.com',
                'password' => Hash::make('auliarizki6991'),
                'email_verified_at' => Carbon::parse('2025-05-20 04:14:07'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'YUDHA NANDA PRATAMA',
                'email' => 'yudhananda1717@gmail.com',
                'password' => Hash::make('yudhananda1717'),
                'email_verified_at' => Carbon::parse('2025-05-30 21:10:35'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'KADINO',
                'email' => 'kadino30031983@gmail.com',
                'password' => Hash::make('kadino30031983'),
                'email_verified_at' => Carbon::parse('2025-06-10 14:07:03'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ELLY LATIPA',
                'email' => 'ellylatipa@gmail.com',
                'password' => Hash::make('ellylatipa'),
                'email_verified_at' => Carbon::parse('2025-06-21 07:03:31'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TAUFIK FURQAN',
                'email' => 'furqantaufik44@gmaol.com',
                'password' => Hash::make('furqantaufik44@gmaol.com'),
                'email_verified_at' => Carbon::parse('2025-07-02 00:00:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'WAHYU EKA PERMANA',
                'email' => 'wahyuekapermana16@gmail.com',
                'password' => Hash::make('wahyuekapermana16'),
                'email_verified_at' => Carbon::parse('2025-07-12 16:56:28'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DIAJENG NYIMAS AYU',
                'email' => 'syahiraayu1400@gmail.com',
                'password' => Hash::make('syahiraayu1400'),
                'email_verified_at' => Carbon::parse('2025-07-23 09:52:56'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'OTIB',
                'email' => 'otibmahendra@gmail.com',
                'password' => Hash::make('otibmahendra'),
                'email_verified_at' => Carbon::parse('2025-08-03 02:49:24'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RITA NATALINA MARUHAWA',
                'email' => 'ritanatalina802@gmail.com',
                'password' => Hash::make('ritanatalina802'),
                'email_verified_at' => Carbon::parse('2025-08-13 19:45:52'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RUDI SAMHUDI',
                'email' => 'rudisamhudirudi78135@gmail.com',
                'password' => Hash::make('rudisamhudirudi78135'),
                'email_verified_at' => Carbon::parse('2025-08-24 12:42:21'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HELNA RIFANI SYAHPUTRI',
                'email' => 'helnarifanis@gmail.com',
                'password' => Hash::make('helnarifanis'),
                'email_verified_at' => Carbon::parse('2025-09-04 05:38:49'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'M. FAJAR',
                'email' => 'm.fahar27071999@gmail.com',
                'password' => Hash::make('m.fahar27071999'),
                'email_verified_at' => Carbon::parse('2025-09-14 22:35:17'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'YUS HERIANTO HAREFA',
                'email' => 'yusheriyantoharefa@gmail.com',
                'password' => Hash::make('yusheriyantoharefa'),
                'email_verified_at' => Carbon::parse('2025-09-25 15:31:45'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'YOSAMA NDRURU',
                'email' => 'yosamandruru35@gmail.com',
                'password' => Hash::make('yosamandruru35'),
                'email_verified_at' => Carbon::parse('2025-10-06 08:28:14'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ANITHA AMELIA ESSING',
                'email' => 'anithaamelia7@gmail.com',
                'password' => Hash::make('anithaamelia7'),
                'email_verified_at' => Carbon::parse('2025-10-17 01:24:42'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TAI NOVIANA',
                'email' => 'vina.nathan2020@gmail.com',
                'password' => Hash::make('vina.nathan2020'),
                'email_verified_at' => Carbon::parse('2025-10-27 18:21:10'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ARISTARKUS MAMOGA',
                'email' => 'arismamoga@gmail.com',
                'password' => Hash::make('arismamoga'),
                'email_verified_at' => Carbon::parse('2025-11-07 11:17:38'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'VEMY L.BUAMBITUN',
                'email' => 'lbvemy@gmail.com',
                'password' => Hash::make('lbvemy'),
                'email_verified_at' => Carbon::parse('2025-11-18 04:14:07'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SURIHATI HALAWA',
                'email' => 'surihatihalawa@gmail.com',
                'password' => Hash::make('surihatihalawa'),
                'email_verified_at' => Carbon::parse('2025-11-28 21:10:35'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'KRISTIANIWARUWU',
                'email' => 'kristianiwaruwuo4@gmail.com',
                'password' => Hash::make('kristianiwaruwuo4'),
                'email_verified_at' => Carbon::parse('2025-12-09 14:07:03'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MARIANA KOROMPIS',
                'email' => 'mariana.korompis08@gmail.com',
                'password' => Hash::make('mariana.korompis08'),
                'email_verified_at' => Carbon::parse('2025-12-20 07:03:31'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DESI LIDIA MAMARODIA',
                'email' => 'desimamarodia7@gmail.com',
                'password' => Hash::make('desimamarodia7'),
                'email_verified_at' => Carbon::parse('2025-12-31 00:00:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LATIEF BUHORI',
                'email' => 'latief.buff88@gmail.com',
                'password' => Hash::make('latief.buff88'),
                'email_verified_at' => Carbon::parse('2023-12-01 12:00:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AGUNG PRAYETNO',
                'email' => 'aprayetno871@gmail.com',
                'password' => Hash::make('aprayetno871'),
                'email_verified_at' => Carbon::parse('2025-02-02 07:17:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DEWI SRI INDAH',
                'email' => 'dewisriindah1@gmail.com',
                'password' => Hash::make('dewisriindah1'),
                'email_verified_at' => Carbon::parse('2025-12-31 00:00:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RIO ARYANTO',
                'email' => 'aryanto5991@gmail.com',
                'password' => Hash::make('aryanto5991'),
                'email_verified_at' => Carbon::parse('2024-01-15 10:23:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MUHAMAD JALALUDIN KAMIL',
                'email' => 'jalalkamil4002@gmail.com',
                'password' => Hash::make('jalalkamil4002'),
                'email_verified_at' => Carbon::parse('2023-11-20 14:12:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NISRINA MUMTAZ',
                'email' => 'mnisrina935@gmail.com',
                'password' => Hash::make('mnisrina935'),
                'email_verified_at' => Carbon::parse('2024-07-03 08:45:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CHAERUL FAZRY',
                'email' => 'chaerulfazry12@gmail.com',
                'password' => Hash::make('chaerulfazry12'),
                'email_verified_at' => Carbon::parse('2025-03-12 17:30:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NANANG ABDULLAH',
                'email' => 'nanangabdullah76@gmail.com',
                'password' => Hash::make('nanangabdullah76'),
                'email_verified_at' => Carbon::parse('2023-09-09 09:00:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'KOKO KUSNANDAR',
                'email' => 'kokokusnandar39@gmail.com',
                'password' => Hash::make('kokokusnandar39'),
                'email_verified_at' => Carbon::parse('2025-08-18 21:20:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HENDRA YANA',
                'email' => 'hyana4977@gmail.com',
                'password' => Hash::make('hyana4977'),
                'email_verified_at' => Carbon::parse('2024-05-25 15:55:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ASEP MUHAMAD HARIS',
                'email' => 'asepmuhamadharis29@gmail.com',
                'password' => Hash::make('asepmuhamadharis29'),
                'email_verified_at' => Carbon::parse('2023-12-01 12:00:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TITIN ANI KOTIN',
                'email' => 'titinanikotin@gmail.com',
                'password' => Hash::make('titinanikotin'),
                'email_verified_at' => Carbon::parse('2025-02-02 07:17:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MEISKE PAKASI',
                'email' => 'maiskepakasi3@gmail.com',
                'password' => Hash::make('maiskepakasi3'),
                'email_verified_at' => Carbon::parse('2025-12-31 00:00:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ANGGUN PERTIWI',
                'email' => 'anggunpertiwi942@gmail.com',
                'password' => Hash::make('anggunpertiwi942'),
                'email_verified_at' => Carbon::parse('2024-01-15 10:23:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SHEILA SRIWULANDARI PUTRI',
                'email' => 'Sheilasrii032@gmail.com',
                'password' => Hash::make('sheilasrii032'),
                'email_verified_at' => Carbon::parse('2023-11-20 14:12:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MUHAMMAD UBAYDILLAH ALGHANI',
                'email' => 'ubaydillahalghani03@gmail.com',
                'password' => Hash::make('ubaydillahalghani03'),
                'email_verified_at' => Carbon::parse('2024-07-03 08:45:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SALIM ISKANDAR',
                'email' => 'hafidzismail0705@gmail.com',
                'password' => Hash::make('hafidzismail0705'),
                'email_verified_at' => Carbon::parse('2025-03-12 17:30:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NITA AMELIA',
                'email' => 'nitaamelia412s@gmail.com',
                'password' => Hash::make('nitaamelia412s'),
                'email_verified_at' => Carbon::parse('2023-09-09 09:00:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'UMMI LATIFATUL MARZUQOH',
                'email' => 'umilatifatulmarzuqoh@gmail.com',
                'password' => Hash::make('umilatifatulmarzuqoh'),
                'email_verified_at' => Carbon::parse('2025-08-18 21:20:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AYU NUR FITRIANI',
                'email' => 'ayunurfitriani23@gmail.com',
                'password' => Hash::make('ayunurfitriani23'),
                'email_verified_at' => Carbon::parse('2024-05-25 15:55:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TEGUH BURHAN SYAH',
                'email' => 'teguhburhansyah86@gmail.com',
                'password' => Hash::make('teguhburhansyah86'),
                'email_verified_at' => Carbon::parse('2023-12-01 12:00:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SYALWA SALSABILA',
                'email' => 'syalwasalsabila0@gmail.com',
                'password' => Hash::make('syalwasalsabila0'),
                'email_verified_at' => Carbon::parse('2025-02-02 07:17:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'YOGA PRATAMA',
                'email' => 'kibonnaxdongkal14@gmail.com',
                'password' => Hash::make('kibonnaxdongkal14'),
                'email_verified_at' => Carbon::parse('2025-12-31 00:00:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NURLIA APRIANI',
                'email' => 'nurliaapriani8@gmail.com',
                'password' => Hash::make('nurliaapriani8'),
                'email_verified_at' => Carbon::parse('2024-01-15 10:23:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JULI AISAH',
                'email' => 'juliaisah47@gmail.com',
                'password' => Hash::make('juliaisah47'),
                'email_verified_at' => Carbon::parse('2023-11-20 14:12:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Eni Indarti',
                'email' => 'eniindarti2107@gmail.com',
                'password' => Hash::make('eniindarti2107'),
                'email_verified_at' => Carbon::parse('2024-07-03 08:45:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RIRIN ARIYANI',
                'email' => 'ririnufy354@gmail.com',
                'password' => Hash::make('ririnufy354'),
                'email_verified_at' => Carbon::parse('2025-03-12 17:30:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SARNIH SARI RAHAYU',
                'email' => 'sarirahayusarnih5@gmail.com',
                'password' => Hash::make('sarirahayusarnih5'),
                'email_verified_at' => Carbon::parse('2023-09-09 09:00:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Puryanti',
                'email' => 'Puryade21@gmail.com',
                'password' => Hash::make('puryade21'),
                'email_verified_at' => Carbon::parse('2025-08-18 21:20:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MUHAMAD HAIKAL',
                'email' => 'haikalbm22@gmail.com',
                'password' => Hash::make('haikalbm22'),
                'email_verified_at' => Carbon::parse('2024-05-25 15:55:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'EVA KOMALA PRANANDA',
                'email' => 'evakomalaprananda.eva9@gmail.com',
                'password' => Hash::make('evakomalaprananda.eva9'),
                'email_verified_at' => Carbon::parse('2023-12-01 12:00:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SUHENDI',
                'email' => 'suhendi01051986@gmail.com',
                'password' => Hash::make('suhendi01051986'),
                'email_verified_at' => Carbon::parse('2025-02-02 07:17:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LIYA ANDINI',
                'email' => 'liyaandini123@gmail.com',
                'password' => Hash::make('liyaandini123'),
                'email_verified_at' => Carbon::parse('2025-12-31 00:00:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ADIM EDI SURYANA',
                'email' => 'aaaiiimmm092@gmail.com',
                'password' => Hash::make('aaaiiimmm092'),
                'email_verified_at' => Carbon::parse('2024-01-15 10:23:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'YOSI NOVIANITA LESMANA',
                'email' => 'mishaindira@gmail.com',
                'password' => Hash::make('mishaindira'),
                'email_verified_at' => Carbon::parse('2023-11-20 14:12:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DESI LIANA',
                'email' => 'desiliana120795@gmail.com',
                'password' => Hash::make('desiliana120795'),
                'email_verified_at' => Carbon::parse('2024-07-03 08:45:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Roh iman waruwu',
                'email' => 'waruwurohiman@gmail.com',
                'password' => Hash::make('waruwurohiman'),
                'email_verified_at' => Carbon::parse('2025-03-12 17:30:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MARIA KRISTIN ROTUA B',
                'email' => 'mariaaa.kristinn@gmail.com',
                'password' => Hash::make('mariaaa.kristinn'),
                'email_verified_at' => Carbon::parse('2023-09-09 09:00:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RAMDAN ABDUL MALIK',
                'email' => 'malikramdan12345@gmail.com',
                'password' => Hash::make('malikramdan12345'),
                'email_verified_at' => Carbon::parse('2025-08-18 21:20:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CLARISSA EMANUELA TALUMEPA',
                'email' => 'clarissatalumepa@gmail.com',
                'password' => Hash::make('clarissatalumepa'),
                'email_verified_at' => Carbon::parse('2024-05-25 15:55:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ERIZONA FATMAWATI',
                'email' => 'rismaafatmawati@gmail.com',
                'password' => Hash::make('rismaafatmawati'),
                'email_verified_at' => Carbon::parse('2023-12-01 12:00:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ORIANA REBECHA',
                'email' => 'rebechaoriana@gmail.com',
                'password' => Hash::make('rebechaoriana'),
                'email_verified_at' => Carbon::parse('2025-02-02 07:17:00'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                    'name' => 'ACAH',
                    'email' => 'Saningsamsudin@gmail.com',
                    'password' => Hash::make('saningsamsudin'),
                    'email_verified_at' => Carbon::parse('2024-01-15 10:23:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PUTRI SRI RAHAYU',
                    'email' => 'putrisr0190@gmail.com',
                    'password' => Hash::make('putrisr0190'),
                    'email_verified_at' => Carbon::parse('2023-11-20 14:12:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'AAN LAELASARI',
                    'email' => 'aanlaelasari936@gmail.com',
                    'password' => Hash::make('aanlaelasari936'),
                    'email_verified_at' => Carbon::parse('2024-07-03 08:45:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'SULTAN ANDIKA PUTRA',
                    'email' => 'sultanandikaputra2@gmail.com',
                    'password' => Hash::make('sultanandikaputra2'),
                    'email_verified_at' => Carbon::parse('2025-03-12 17:30:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'TITIN SULASTRI',
                    'email' => 'tsulastriI314@gmail.com',
                    'password' => Hash::make('tsulastriI314'),
                    'email_verified_at' => Carbon::parse('2023-09-09 09:00:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'DEVI YULIANI',
                    'email' => 'deviyuliani3001997@gmail.com',
                    'password' => Hash::make('deviyuliani3001997'),
                    'email_verified_at' => Carbon::parse('2025-08-18 21:20:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'SAMAH',
                    'email' => 'zidanemuhammad245@gmail.com',
                    'password' => Hash::make('zidanemuhammad245'),
                    'email_verified_at' => Carbon::parse('2023-05-04 15:57:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'DEDEN HIDAYAT',
                    'email' => 'dedenhidayat15061982@gmail.com',
                    'password' => Hash::make('dedenhidayat15061982'),
                    'email_verified_at' => Carbon::parse('2023-01-30 12:00:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'KARTINI',
                    'email' => 'kt742882@gmail.com',
                    'password' => Hash::make('kt742882'),
                    'email_verified_at' => Carbon::parse('2025-02-02 07:17:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'MUHAMAD ZAKARIA',
                    'email' => 'zakariamuhamad0011@gmail.com',
                    'password' => Hash::make('zakariamuhamad0011'),
                    'email_verified_at' => Carbon::parse('2025-12-31 00:00:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'NUR MALASARI',
                    'email' => 'nmalasari686@gmail.com',
                    'password' => Hash::make('nmalasari686'),
                    'email_verified_at' => Carbon::parse('2024-01-15 10:23:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'M. FAZRI',
                    'email' => 'mfazri220905@gmail.com',
                    'password' => Hash::make('mfazri220905'),
                    'email_verified_at' => Carbon::parse('2023-11-20 14:12:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'DEAN SETIAWAN',
                    'email' => 'deansetiawan253@gmail.com',
                    'password' => Hash::make('deansetiawan253'),
                    'email_verified_at' => Carbon::parse('2024-07-03 08:45:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'RASIH',
                    'email' => 'yanyansetwan@gmail.com',
                    'password' => Hash::make('yanyansetwan'),
                    'email_verified_at' => Carbon::parse('2025-03-12 17:30:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'SALSA AULIA.P',
                    'email' => 'salsaauliaputri943@gmail.com',
                    'password' => Hash::make('salsaauliaputri943'),
                    'email_verified_at' => Carbon::parse('2023-09-09 09:00:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'DELVANI AUSTINA',
                    'email' => 'delvaniaustina10@gmail.com',
                    'password' => Hash::make('delvaniaustina10'),
                    'email_verified_at' => Carbon::parse('2025-08-18 21:20:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'ANISA',
                    'email' => 'anisyaanggraini1099@gmail.com',
                    'password' => Hash::make('anisyaanggraini1099'),
                    'email_verified_at' => Carbon::parse('2024-05-25 15:55:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'IYAN ANDRIANSYAH',
                    'email' => 'gsafitri036@gmail.com',
                    'password' => Hash::make('gsafitri036'),
                    'email_verified_at' => Carbon::parse('2023-12-01 12:00:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'SERGIO RAMOT ANDIKA',
                    'email' => 'posmahansa@gmail.com',
                    'password' => Hash::make('posmahansa'),
                    'email_verified_at' => Carbon::parse('2025-02-02 07:17:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'SHILVIA FATIKA RIZKY',
                    'email' => 'shilviafatikah31@gmail.com',
                    'password' => Hash::make('shilviafatikah31'),
                    'email_verified_at' => Carbon::parse('2025-12-31 00:00:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'ARLAN ARMANSYAH',
                    'email' => 'arlanarmnsyh@gmail.com',
                    'password' => Hash::make('arlanarmnsyh'),
                    'email_verified_at' => Carbon::parse('2024-01-15 10:23:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'AFRIZAL MAULANA',
                    'email' => 'Afrizalm0010@gmail.com',
                    'password' => Hash::make('afrizalm0010'),
                    'email_verified_at' => Carbon::parse('2023-11-20 14:12:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'NANDA FEBRIANTI',
                    'email' => 'nandafebriyanti45@gmail.com',
                    'password' => Hash::make('nandafebriyanti45'),
                    'email_verified_at' => Carbon::parse('2024-07-03 08:45:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'DWI YANTO ASHARUL RAMADHAN',
                    'email' => 'dwiiyantogabung21@gmail.com',
                    'password' => Hash::make('dwiiyantogabung21'),
                    'email_verified_at' => Carbon::parse('2025-03-12 17:30:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'IMIH LESTARI',
                    'email' => 'imihrestari@gmail.com',
                    'password' => Hash::make('imihrestari'),
                    'email_verified_at' => Carbon::parse('2023-09-09 09:00:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'NATA',
                    'email' => 'nata85366@gmail.com',
                    'password' => Hash::make('nata85366'),
                    'email_verified_at' => Carbon::parse('2025-08-18 21:20:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'NYI INDAH .R',
                    'email' => 'nyiidahr1@gmail.com',
                    'password' => Hash::make('nyiidahr1'),
                    'email_verified_at' => Carbon::parse('2024-05-25 15:55:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'DWI LESTARI',
                    'email' => 'Dwi489944@gmail.com',
                    'password' => Hash::make('dwi489944'),
                    'email_verified_at' => Carbon::parse('2023-12-01 12:00:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'CHRISNA ARDHILLA',
                    'email' => 'chrisnaardhilla811@gmail.com',
                    'password' => Hash::make('chrisnaardhilla811'),
                    'email_verified_at' => Carbon::parse('2025-02-02 07:17:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'ARIS GUNAWAN',
                    'email' => 'gunawanaris4891@gmail.com',
                    'password' => Hash::make('gunawanaris4891'),
                    'email_verified_at' => Carbon::parse('2025-12-31 00:00:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'DIANA AFRILYANI',
                    'email' => 'dianaafril242@gmail.com',
                    'password' => Hash::make('dianaafril242'),
                    'email_verified_at' => Carbon::parse('2024-01-15 10:23:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'RAFLI MAHES ABIDIN',
                    'email' => 'rmahesabidin@gmail.com',
                    'password' => Hash::make('rmahesabidin'),
                    'email_verified_at' => Carbon::parse('2023-11-20 14:12:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'PIYANTI',
                    'email' => 'piyanti1997@gmail.com',
                    'password' => Hash::make('piyanti1997'),
                    'email_verified_at' => Carbon::parse('2024-07-03 08:45:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'TITI SULASTRI',
                    'email' => 'sulastrititi453@gmail.com',
                    'password' => Hash::make('sulastrititi453'),
                    'email_verified_at' => Carbon::parse('2025-03-12 17:30:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'BUDI RACHMAN',
                    'email' => 'rachmanbudi1891@gmail.com',
                    'password' => Hash::make('rachmanbudi1891'),
                    'email_verified_at' => Carbon::parse('2023-09-09 09:00:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'DARMAJI',
                    'email' => 'darmaji191981@gmail.com',
                    'password' => Hash::make('darmaji191981'),
                    'email_verified_at' => Carbon::parse('2025-08-18 21:20:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'IDA NURAIDA',
                    'email' => 'idanur4375@gmail.com',
                    'password' => Hash::make('idanur4375'),
                    'email_verified_at' => Carbon::parse('2024-05-25 15:55:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'RUDI SUHERLAN',
                    'email' => 'rudisuherlan40@gmail.com',
                    'password' => Hash::make('rudisuherlan40'),
                    'email_verified_at' => Carbon::parse('2023-12-01 12:00:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'FAHMI ARDIANSYAH',
                    'email' => 'ardiansyahfahmi01@gmail.com',
                    'password' => Hash::make('ardiansyahfahmi01'),
                    'email_verified_at' => Carbon::parse('2025-02-02 07:17:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'RIAH',
                    'email' => 'riah44687@gmail.com',
                    'password' => Hash::make('riah44687'),
                    'email_verified_at' => Carbon::parse('2025-12-31 00:00:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'SITI KOMARIAH',
                    'email' => 'sitikomariah021979@gmail.com',
                    'password' => Hash::make('sitikomariah021979'),
                    'email_verified_at' => Carbon::parse('2024-01-15 10:23:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'LOLA RIANTI',
                    'email' => 'saputrasurya15@gmail.com',
                    'password' => Hash::make('saputrasurya15'),
                    'email_verified_at' => Carbon::parse('2023-11-20 14:12:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'IMAM RAMADHAN',
                    'email' => 'imamr0228@gmail.com',
                    'password' => Hash::make('imamr0228'),
                    'email_verified_at' => Carbon::parse('2024-07-03 08:45:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'YENNY FATICASARI',
                    'email' => 'yennyfaticasari5@gmail.com',
                    'password' => Hash::make('yennyfaticasari5'),
                    'email_verified_at' => Carbon::parse('2025-03-12 17:30:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'IYUT TRISNAWATI',
                    'email' => 'iyutiyut612@gmail.com',
                    'password' => Hash::make('iyutiyut612'),
                    'email_verified_at' => Carbon::parse('2023-09-09 09:00:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'HENI',
                    'email' => 'henih5824@gmail.com',
                    'password' => Hash::make('henih5824'),
                    'email_verified_at' => Carbon::parse('2025-08-18 21:20:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'YAYAH ROKAYAH',
                    'email' => 'sofiyahfauziyah@gmail.com.',
                    'password' => Hash::make('sofiyahfauziyah'),
                    'email_verified_at' => Carbon::parse('2024-05-25 15:55:00'),
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            
        ];

        DB::table('users')->insert($users);
    }
}
