[phases.setup]
aptPkgs = ["unzip", "libicu-dev", "libzip-dev"]

[phases.build]
cmds = [
  "docker-php-ext-install intl zip pdo_mysql"
]

[phases.install]
cmds = [
  "composer install --optimize-autoloader --no-scripts --no-interaction"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
